// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundPatternCross: typeof import('./components/BackgroundPattern/Cross.vue')['default']
    BackgroundPatternPolygon3d: typeof import('./components/BackgroundPattern/Polygon3d.vue')['default']
    BackgroundPatternSquare: typeof import('./components/BackgroundPattern/Square.vue')['default']
    BackgroundPatternStripCircle: typeof import('./components/BackgroundPattern/StripCircle.vue')['default']
    BackgroundPatternStripDot: typeof import('./components/BackgroundPattern/StripDot.vue')['default']
    BackgroundPatternZigzag: typeof import('./components/BackgroundPattern/Zigzag.vue')['default']
    BaseButton: typeof import('./components/Base/Button.vue')['default']
    BaseCarouselProjectItem: typeof import('./components/Base/CarouselProjectItem.vue')['default']
    BaseLottieFiles: typeof import('./components/Base/LottieFiles.vue')['default']
    BaseNavbarHamburgerItem: typeof import('./components/Base/NavbarHamburgerItem.vue')['default']
    BaseNavbarSocialItem: typeof import('./components/Base/NavbarSocialItem.vue')['default']
    BaseOthersCard: typeof import('./components/Base/OthersCard.vue')['default']
    BaseSkillCard: typeof import('./components/Base/SkillCard.vue')['default']
    BaseSkillIcon: typeof import('./components/Base/SkillIcon.vue')['default']
    BuilderWrapper: typeof import('./components/Builder/Wrapper.vue')['default']
    SectionHomeAbout: typeof import('./components/Section/Home/About.vue')['default']
    SectionHomeContact: typeof import('./components/Section/Home/Contact.vue')['default']
    SectionHomeLanding: typeof import('./components/Section/Home/Landing.vue')['default']
    SectionHomeOthers: typeof import('./components/Section/Home/Others.vue')['default']
    SectionHomeProjects: typeof import('./components/Section/Home/Projects.vue')['default']
    SectionHomeSkills: typeof import('./components/Section/Home/Skills.vue')['default']
    SectionNavbar: typeof import('./components/Section/Navbar.vue')['default']
    TitleUnderline: typeof import('./components/TitleUnderline.vue')['default']
  }
}

export { }
