// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BackgroundPatternCross: typeof import('./components/BackgroundPattern/Cross.vue')['default']
    BackgroundPatternPolygon3d: typeof import('./components/BackgroundPattern/Polygon3d.vue')['default']
    BackgroundPatternSquare: typeof import('./components/BackgroundPattern/Square.vue')['default']
    BackgroundPatternStripCircle: typeof import('./components/BackgroundPattern/StripCircle.vue')['default']
    BackgroundPatternStripDot: typeof import('./components/BackgroundPattern/StripDot.vue')['default']
    BackgroundPatternZigzag: typeof import('./components/BackgroundPattern/Zigzag.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    SectionNavbar: typeof import('./components/Section/Navbar.vue')['default']
  }
}

export { }
